### PR TITLE
Upgrade lotus (master)

### PR DESCRIPTION
**Pull request by rvagg**
Jumping to master to deal with https://github.com/filecoin-shipyard/js-lotus-client-schema/pull/19#issuecomment-945900017, but we should update it again when 1.13 is properly tagged, we're close.

### CODE REVIEW

**Comment by rvagg** [comment]
pulled in the web3-bot/sync branch from #19 to see if it gets addressed by this update

**Comment by rvagg** [comment]
@marten-seemann:

```
  C:\Users\runneradmin\go\pkg\mod\github.com\filecoin-project\lotus@v1.12.1-0.20211018150248-98ff1c4d2035\extern\sector-storage\fsutil\filesize_unix.go:24:29: undefined: syscall.Stat_t
```

**Comment by marten-seemann** [comment]
@rvagg Looks like there's no Windows implementation of `FileSize`, so I assume adding the `build` tag (equivalent to https://github.com/filecoin-project/lotus/pull/7531) wouldn't work here: https://github.com/filecoin-project/lotus/tree/master/extern/sector-storage/fsutil.

**Comment by rvagg** [comment]
i think the fix is local here, I just need to get around to it, we don't need this to build or run on windows, that's not the purpose of the Go code in here, we just need CI to ignore it on windows

**Comment by galargh** [comment]
Do you think it would be desirable for the CI Workflows framework to support platform list customisation? Or would we rather ignore the tests in Go when we detect we're running on Windows? Sorry if I misunderstood the conclusion here.

**Comment by marten-seemann** [comment]
@galargh In general, our software is supposed to build on Linux, Windows, Mac (at least this applies to libp2p, IPLD and IPFS). If this policy is different in Filecoin, we might need to think about excluding Windows from CI builds.

**Comment by rvagg** [comment]
don't take this specific instance as representative - I think this can be fixed locally with a Go build flag, it's just super-low priority for my personal brainspace allocation .. I'll get to it, or someone else might before me

**Comment by rvagg** [comment]
closed vi #23

**Pull request closed without merging**
